### PR TITLE
Turkish Translations are added

### PR DESCRIPTION
**Pull request by onuromer**
Created the tr.ts file, updated locales.ts to include turkish translations.

### CODE REVIEW

**Review by onuromer — COMMENTED** [review]
Fixed a typo for a case sensitive key: manageDatesStatusIncompatible

**Comment by albertospelta** [comment]
Thanks @onuromer !!

**Comment by onuromer** [comment]
> Thanks @onuromer !!

you are welcome!!

**Comment by albertospelta** [comment]
Added in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)

**Pull request merged**
