### PR TITLE
Update Bravo UI Chinese Translation & Add Chinese date localization 01 - 04

### PR DESCRIPTION
**Pull request by adamsmodi**
Hello SQLBI team,

this is Mo Di and thanks a lot for merging my 1st Chinese translation two weeks ago..

In this pull request, I have modified a little bit error in the UI translation and also add Chinese date localization configuration.

Holidays, not yet in this time.. But I will send a question mail afterwards..

Pls kindly check and let me know if I still need to do some local changes.

thanks a lot !

### CODE REVIEW

**Comment by albertospelta** [comment]
Hi @adamsmodi, thanks for the PR! 
We need to make some changes because the PR cannot be merged due to a conflict that must be resolved. 

Can you [fork the Dax Template](https://github.com/sql-bi/DaxTemplate/fork) repository and submit to that repo a new pull request with the `DateLocalization` JSON files ? We'll apply the differences and copy them back into the Bravo repository later.
After the 1.0 release of Bravo we will maintain the template files directly in the Bravo repository, but currently all PRs for the Date and Holidays template must be submitted to the DaxTemplate repo. Thanks!

**Comment by albertospelta** [comment]
@adamsmodi Regarding the changes to the `zh.ts` file, I created a new PR (see #377) where I copied your file from this PR - you should have received a request to review the changes. 
The conflict for this PR is due to the use of the `develop` branch as the base branch which has been deleted and no longer exists in the upstream repository - sorry about that!

**Comment by adamsmodi** [comment]
> Hi @adamsmodi, thanks for the PR! We need to make some changes because the PR cannot be merged due to a conflict that must be resolved.
> 
> Can you [fork the Dax Template](https://github.com/sql-bi/DaxTemplate/fork) repository and submit to that repo a new pull request with the `DateLocalization` JSON files ? We'll apply the differences and copy them back into the Bravo repository later. After the 1.0 release of Bravo we will maintain the template files directly in the Bravo repository, but currently all PRs for the Date and Holidays template must be submitted to the DaxTemplate repo. Thanks!

Hello, SQLBI team, I have forked DaxTemplate repository and created PR there using the same date localization.json file. Pls kindly check. Thanks a lot!
thanks a lot

**Comment by adamsmodi** [comment]
> @adamsmodi Regarding the changes to the `zh.ts` file, I created a new PR (see #377) where I copied your file from this PR - you should have received a request to review the changes. The conflict for this PR is due to the use of the `develop` branch as the base branch which has been deleted and no longer exists in the upstream repository - sorry about that!

Hello Alberto,  PR #377 is reviewed and approved. Sorry for your double work and really appreciate your clear guidance. thanks a lot!

**Comment by albertospelta** [comment]
I am closing this as all changes are merged with #377 and https://github.com/sql-bi/DaxTemplate/pull/16

**Pull request closed without merging**
